name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
    - uses: IgnusG/jest-report-action@v2.3.1
      if: always() # Or use "continue-on-error: true" in previous test step
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}