name: Test

on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1

      - name: Test Code
        run: npm run test:ci
        if: always()

      - name: Save Code testing Report JSON
        run: npm run test:report
        if: always()

      - uses: IgnusG/jest-report-action@v2.3.1
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          run-name: Run tests